### PR TITLE
Add default command support

### PR DESCRIPTION
**Pull request by thibmo**
This PR aims to add support for default tasks.
The default task is provided by adding an entry to the command array with `__default` as key.

Example:
```php
<?php
return [
  'settings' => [
    'debug' => true,
    'displayErrorDetails' => true,
    'addContentLengthHeader' => true
  ],
  'commands' => [
    '__default' => \Example\Controller\Cli\Help::class,

    'Help' => \Example\Controller\Cli\Help::class,
    'Test' => \Example\Controller\Cli\Test::class,
  ]
];
```

### CODE REVIEW

**Comment by adrianfalleiro** [comment]
@thibmo Can you fix the README conflict?

**Comment by thibmo** [comment]
Yep. :)

**Comment by thibmo** [comment]
There we go.

**Comment by adrianfalleiro** [comment]
Merged.

**Pull request merged**
