### PR TITLE
Fix get commands from settings

### PR DESCRIPTION
**Pull request by joubertredrat**

### CODE REVIEW

**Comment by thibmo** [comment]
I'm against this PR.
In my opinion we shouldn't mess with the framework's settings. The current way of doing things is better.

Plus, what's the benefit of this over the following config?
```php
<?php
$app = new App([
    'settings' => [
        'debug' => true,
        'displayErrorDetails' => true,
        'addContentLengthHeader' => true
    ],
    // CLI config
    'commands' => [
        'Help' => \Example\Controller\Cli\Help::class,
        'Test' => \Example\Controller\Cli\Test::class,
        'Doctrine::generate' => \Example\Controller\Cli\Doctrine\Generate::class,
        'Doctrine::deploy' => \Example\Controller\Cli\Doctrine\Deploy::class,
        'Doctrine::generateMigration' => \Example\Controller\Cli\Doctrine\GenerateMigration::class,
        'Doctrine::migrate' => \Example\Controller\Cli\Doctrine\Migrate::class,
        'Email::processQueue' => \Example\Controller\Cli\Email\ProcessQueue::class
    ]
]);
```

**Comment by thibmo** [comment]
I do agree with you on the docs requiring an overhaul.
There should also be a decent example app, rather then 2 command classes. That way people who are new to this can more easily get into it. I'll see what I can do when I'm home. :) (Btw, I'm just a contributor, the maintainer would need to agree before anything gets pulled)

**Comment by adrianfalleiro** [comment]
I will happy accept a PR with better documentation and examples :)

**Comment by thibmo** [comment]
Sure thing, I'll work on it. :)

**Pull request closed without merging**
